from distutils.core import setup

setup(name = 'ShotServer',
      version = '0.3-alpha1',
      description = 'Server software for browsershots.org',
      author = 'Johann C. Rocholl',
      author_email = 'johann@browsershots.org',
      url = 'http://v03.browsershots.org/',
      package_dir = {'shotserver03': 'shotserver03'},
      packages = [
            'shotserver03',
            'shotserver03.get',
            'shotserver03.post',
            'shotserver03.database',
            'shotserver03.interface',
            'shotserver03.request',
            'shotserver03.segments',
            'shotserver03.xmlrpc',
            'shotserver03.util',
            ],
      scripts = [
            'scripts/shotserver03_daily.sh',
            'scripts/shotserver03_db_backup.sh',
            'scripts/shotserver03_db_cleanup.sh',
            'scripts/shotserver03_db_vacuum.sh',
            'scripts/shotserver03_db_statistics.sh',
            'scripts/shotserver03_trac_backup.sh',
            'scripts/shotserver03_svn_backup.sh',
            'scripts/shotserver03_mailman_backup.sh',
            'scripts/shotserver03_grep_error_log.sh',
            'scripts/shotserver03_log_dates.py',
            'scripts/shotserver03_apache2_log_backup.sh',
            'scripts/shotserver03_rm_old_png.py',
            'scripts/svn_backup.py',
            ],
      data_files = [
            ('share/shotserver03/style', [
                  'style/style.css',
                  'style/logo40.png',
                  'style/mfg40.png',
                  'style/lisog40.png',
                  'style/topalis40.png',
                  'style/brandup40.png',
                  'style/blue.jpg',
                  'style/gray.jpg',
                  'style/zoom.js',
                  'style/forms.js',
                  'style/favicon.ico',
                  ])],
      )
